before_install:
  - yes | sudo add-apt-repository ppa:hansjorg/rust
  - sudo apt-get update
install:
  - sudo apt-get install rust-nightly
env:
 - RUST_TEST_TASKS=1
script:
  - rustc --version
  - make
  - make tests
  - cd test
  - ./libhaml_tests